### ISSUE TITLE
Adjust Lesson 4 - Part 1

### ISSUE THREAD

**Issue by joanapazcardoso** [wlsf82/test-automation-with-protractor#4]
https://github.com/wlsf82/test-automation-with-protractor/blob/main/LESSONS/4.md
cc @wlsf82 

Have you heard of Jasmine, the unit testing library?

So, Protractor uses Jasmine as its default testing library, which means that the structure and syntax are basically the same.

First, you start a test suite, which uses the describe() function.

The describe() function receives a string as its first argument (e.g., 'my app') and a callback function as its second argument.

Inside of the describe's callback function, tests are written in it() functions.

Similar to the describe() function, it() functions also receives a string as its first argument (e.g., 'test login with success') and a callback function as its second argument.

Then, the test logic is written inside of its callback function.

Exercise
Inside of the specs/login.spec.js file, create the basic structure to test the successful login scenario.

🕵🏻‍♀️ Here's a hint.

// specs/login.spec.js

describe('Login', function() {
  it('logs in successfully', function() {

  })
})
Extra credit 1
Go to the terminal inside this project's root directory and run npx webdriver-manager update && npx protractor conf.js.

Started
.

1 spec, 0 failures
Finished in 0.165 seconds

[01:25:57] I/local - Shutting down selenium standalone server.
[01:25:57] I/launcher - 0 instance(s) of WebDriver still running
[01:25:57] I/launcher - chrome #01 passed
Tada! 🎉 You have your first passing test!

Yeah, I know there's no test implemented yet, but it feels good to see it pass. Don't you feel that?

Extra credit 2
Alright, now you need to learn a few of the Protractor functionalities.

First, to visit a web page by its relative URL (since we already have the baseUrl defined in the config file), Protractor uses browser.get('/some-relative-url').

Secondly, to locate HTML elements, Protractor can use a few strategies. Let's see some of them.

const iAmATextInputWithAnId = element(by.id('my-id'))
const iAmAnElementWithAClass = element(by.className('some-class'))
const iAmASubmitButton = element(by.css('button[type="submit"]'))
const iAmAHeadingWithASpecificText = element(by.cssContainingText('h1', 'I am a heading, yay!'))
Thirdly, to interact with the located elements, Protractor have many different methods. Let's explore a couple of them.

// This is how Protractor simulates a user typing in a text input field (or a text area)
iAmATextInputWithAnId.sendKeys('Hi!')

// And this is how Protractor clicks on elements such as buttons, links, etc.
iAmASubmitButton.click()
It's your turn.

Go to https://notes-serverless-app.com/signup and create an account so that you can use the created user for the logs in successfully test.

Then, implement the test's logic so that it will visit the /login relative URL, it will locate the right element, and it will fill the form and submit.

Finally, run test (npx protractor conf.js).

**Comment by wlsf82** [comment]
Closed by https://github.com/wlsf82/test-automation-with-protractor/commit/92ae4cfaa420fd9d1a1a1addb763a9bb48aa62bf
