### ISSUE TITLE
Adjust Read me

### ISSUE THREAD

**Issue by joanapazcardoso** [wlsf82/test-automation-with-protractor#5]
https://github.com/wlsf82/test-automation-with-protractor/blob/main/README.md
cc @wlsf82 

What you will learn during this course
In this course, you'll learn:

How to install and configure Protractor
How to write tests for many different scenarios of a non-angular web app
How to focus on what's more important first
Most important features
Making it work first and refactoring later.
How to organize tests' pre-conditions
How to protect sensitive information
How to use the page objects & components pattern
How to use other open-source libraries to help you write tests
How to test responsive apps
How to test file upload
How to run cross-browser testing in both headful and headless modes
How to improve the command line test report for CI
How to report test results as an HTML page
A mechanism for re-running tests to prove they're not flakey
A feature to allow you to demo the tests you wrote

**Comment by wlsf82** [comment]
Closed by https://github.com/wlsf82/test-automation-with-protractor/commit/92ae4cfaa420fd9d1a1a1addb763a9bb48aa62bf
